apiVersion: v1 
kind: Service 
metadata: 
  name: {{ .Release.Name }}-backend-service 
spec: 
  type: LoadBalancer 
  ports: 
   - protocol: TCP  
     port: {{ .Values.backendPort }} 
     targetPort: {{ .Values.backendTargetPort }} 
  selector: 
    app: {{ .Release.Name }}-backend