{{- range $.Values.roles.developers }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: developer-role-binding-{{ . }}
  namespace: default
subjects:
- kind: User
  name: {{ . }}
roleRef:
  kind: ClusterRole
  name: {{ $.Release.Name }}-developer
  apiGroup: rbac.authorization.k8s.io
---
{{- end }}