apiVersion: v1 
kind: ConfigMap 
metadata: 
  name: {{ .Release.Name }}-postgres-config 
  labels: 
    app: {{ .Release.Name }}-postgres 
data: 
  POSTGRES_DB:  {{ .Values.dBName}}
  POSTGRES_USER:  {{ .Values.dbUser}}
  POSTGRES_PORT: {{ .Values.dbPort | quote}}
  POSTGRES_HOST: {{ .Release.Name }}-postgres-service

