apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    app: {{ .Release.Name }}-postgres
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.dbPort }}
  selector:
    app: {{ .Release.Name }}-postgres
