kind: PersistentVolume 
apiVersion: v1 
metadata: 
  name: {{ .Release.Name }}-postgres-pv-volume 
  labels: 
    type: local 
    app: {{ .Release.Name }}-postgres 
spec: 
  storageClassName: standard 
  capacity: 
    storage: 5Gi 
  accessModes: 
    - ReadWriteMany 
  hostPath: 
    path: "/var/lib/data" 
--- 
kind: PersistentVolumeClaim 
apiVersion: v1 
metadata: 
  name: {{ .Release.Name }}-postgres-pv-claim 
  labels: 
    app: {{ .Release.Name }}-postgres 
spec: 
  storageClassName: standard 
  accessModes: 
    - ReadWriteMany 
  resources: 
    requests: 
      storage: 5Gi
