kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: developer-role-binding
  namespace: default
subjects:

- kind: User
  name: p.liedtke@student.vu.nl

roleRef:
  kind: ClusterRole
  name: developer
  apiGroup: rbac.authorization.k8s.io

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: devops-role-binding
  namespace: default

subjects:

  - kind: User
    name: s.mojzis@student.vu.nl

roleRef:
  kind: ClusterRole
  name: devops-engineer
  apiGroup: rbac.authorization.k8s.io

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: manager-role-binding
  namespace: default
subjects:

  - kind: User
    name: g.savchenko@student.vu.nl
roleRef:
  kind: ClusterRole
  name: manager
  apiGroup: rbac.authorization.k8s.io