apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-tls-secret
type: kubernetes.io/tls
data:
  tls.crt: |-
    {{ $.Files.Get secret.cert | b64enc }}
    
  tls.key: |-
    {{ $.Files.Get secret.key | b64enc }}
    