apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-tls-secret
type: kubernetes.io/tls
data:
  tls.crt: |-
    {{ .Files.Get "tls/cert.pem" | b64enc }}
    
  tls.key: |-
    {{ .Files.Get "tls/key.pem" | b64enc }}
    