apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: todo-ca
spec:
  isCA: true
  commonName: my-selfsigned-ca
  secretName: todo-secret
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer
    group: cert-manager.io